<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="stylesheet" href="http://shakepoint-assets.s3.amazonaws.com/css/styles.css">
    <title>Shakepoint </title>
</head>

<body yahoo>
    <div class="container">
        <table class="table">
            <tr>
                <td><img src="http://shakepoint-assets.s3.amazonaws.com/img/logowhite.png" class="img-logo"></td>
            </tr>
            <tr>
                <td>
                    <h1 class="gracias">Gracias por su compra</h1>
                </td>
            </tr>
            <tr>
                <td><img src="http://shakepoint-assets.s3.amazonaws.com/img/whey.png" class="img-whey"></td>
            </tr>
            <tr>
                <td>
                    <h5 class="fecha">${purchaseDate}</h5>
                    <table class="orange">
                        <tr class="first-child">
                            <td class="first-child">
                                <h6 class="table-head">Producto</h6>
                            </td>
                            <td class="last-child">
                                <h6 class="table-head">Precio</h6>
                            </td>
                        </tr>
                        <tr class="last-child">
                            <td class="first-child">
                                <h6 class="table-body capitalize">${productName}</h6>
                            </td>
                            <td class="last-child">
                                <h6 class="table-body">$${productPrice}</h6>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td>
                    <h5 class="slogan">make it faster</h5>
                </td>
            </tr>
            <tr>
                <td>
                    <ul class="redes">
                        <li>
                            <a href="http://facebook.com" target="_blank">
                                <img src="http://shakepoint-assets.s3.amazonaws.com/img/face.png" class="img-redes">
                            </a>
                        </li>
                        <li>
                            <a href="http://twitter.com" target="_blank">
                                <img src="http://shakepoint-assets.s3.amazonaws.com/img/twitter.png" class="img-redes">
                            </a>
                        </li>
                        <li>
                            <a href="http://instagram.com" target="_blank">
                                <img src="http://shakepoint-assets.s3.amazonaws.com/img/insta.png" class="img-redes">
                            </a>
                        </li>
                    </ul>
                </td>
            </tr>
            <tr>
                <td>
                    <h5 class="servicio">Estamos para servirle, dudas y comentarios al correo:</h5>
                </td>
            </tr>
            <tr>
                <td>
                    <a href="mailto:support@shakepoint.com.mx" class="link-correo"><h5 class="correo">support@shakepoint.com.mx</h5></a>
                </td>
            </tr>
        </table>
    </div>
</body>

</html>